#ifndef ASSIGN_HARDCODE_E2SM_RC_QUERY_DEFINITION_H
#define ASSIGN_HARDCODE_E2SM_RC_QUERY_DEFINITION_H
#include<stdio.h>
#include"output_main.h"
#include "MAIN_STRUCT.h"

xnap_return_et assign_hardcode_value_E2SM_RC_QueryDefinition(_e2ap_E2SM_RC_QueryDefinition_t* p_E2SM_RC_QueryDefinition)
{
    /*=== START SEQUENCE -idx1 -ROOTS1 E2SM-RC-QueryDefinition ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition alias = -1 -mandatory
    /*=== START CHOICE -rootc1 - E2SM-RC-QueryDefinition-ric-queryDefinition-formats ===*/
    #if 1 //hc-choice-ELEM 1 -idx4 -rootc1: E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM_RC_QueryDefinition_Format1 - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.choice_type = E2AP_E2SM_RC_QUERY_DEFINITION_RIC_QUERY_DEFINITION_FORMATS_e2ap_QUERY_REQUEST_FORMAT1;
    /*=== START SEQUENCE -idx5 -ROOTS2 E2SM-RC-QueryDefinition-Format1 ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1 alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item_count = 1;
    /*=== START SEQUENCE -idx7 -ROOTS3 E2SM-RC-QueryDefinition-Format1-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx9- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx9- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item alias = -1 -optional
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].bitmask |= E2AP_E2SM_RC_QUERY_DEFINITION_FORMAT1_ITEM_e2ap_RAN_PARAMETER_DEFINITION_PRESENT;
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition = xnap_mem_get(sizeof(_e2ap_RANParameter_Definition_t)); //memgetforrecu
    /*=== START SEQUENCE -idx11 -ROOTS4 RANParameter-Definition ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition alias = -1 -mandatory
    /*=== START CHOICE -rootc2 - RANParameter-Definition-Choice ===*/
    #if 1 //hc-choice-ELEM 1 -idx14 -rootc2: RANParameter-Definition-Choice->RANParameter_Definition_Choice_LIST - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choice_type = E2AP_RANPARAMETER_DEFINITION_CHOICE_e2ap_CHOICE_LIST;
    /*=== START SEQUENCE -idx15 -ROOTS5 RANParameter-Definition-Choice-LIST ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item_count = 1;
    /*=== START SEQUENCE -idx17 -ROOTS6 RANParameter-Definition-Choice-LIST-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx19- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx19- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 10 -mandatory
    //hc-ranParameter_name -idx21- alias primitive - pid = 10 PrintableString - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Name
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_name =  "hardcode string valueu"; // change printable string here
    //end of hc-ranParameter_name -idx21- alias primitive

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 10
    //hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = -1 -optional
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].bitmask |= E2AP_RANPARAMETER_DEFINITION_CHOICE_LIST_ITEM_e2ap_RAN_PARAMETER_DEFINITION_PRESENT;
    // [RECUSIVE] recursive - re-idx = 1 / SEQUENCE RANParameter_Definition detected in stack, continuing...
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition = xnap_mem_get(sizeof(_e2ap_RANParameter_Definition_t)); //memgetforrecu
    /*=== START SEQUENCE -idx23 -ROOTS7 RANParameter-Definition ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition alias = -1 -mandatory
    /*=== START CHOICE -rootc3 - RANParameter-Definition-Choice ===*/
    #if 1 //hc-choice-ELEM 1 -idx26 -rootc3: RANParameter-Definition-Choice->RANParameter_Definition_Choice_LIST - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choice_type = E2AP_RANPARAMETER_DEFINITION_CHOICE_e2ap_CHOICE_LIST;
    /*=== START SEQUENCE -idx27 -ROOTS8 RANParameter-Definition-Choice-LIST ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item_count = 1;
    /*=== START SEQUENCE -idx29 -ROOTS9 RANParameter-Definition-Choice-LIST-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx31- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx31- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 10 -mandatory
    //hc-ranParameter_name -idx33- alias primitive - pid = 10 PrintableString - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Name
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_name =  "hardcode string valueu"; // change printable string here
    //end of hc-ranParameter_name -idx33- alias primitive

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 10
    //hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = -1 -optional
    // [STOP] recursive SEQUENCE RANParameter_Definition in stack
    //end of hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = -1
    /*=== END SEQUENCE -idx29 RANParameter-Definition-Choice-LIST-Item -ROOTS9 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST alias = -1
    /*=== END SEQUENCE -idx27 RANParameter-Definition-Choice-LIST -ROOTS8 ===*/

    #endif /*choice-ELEM 1 -idx26 -rootc3 - RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST */

    #if 0 //hc-choice-ELEM 2 -idx35 -rootc3: RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choice_type = E2AP_RANPARAMETER_DEFINITION_CHOICE_e2ap_CHOICE_STRUCTURE;
    /*=== START SEQUENCE -idx36 -ROOTS10 RANParameter-Definition-Choice-STRUCTURE ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item_count = 1;
    /*=== START SEQUENCE -idx38 -ROOTS11 RANParameter-Definition-Choice-STRUCTURE-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx40- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx40- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 10 -mandatory
    //hc-ranParameter_name -idx42- alias primitive - pid = 10 PrintableString - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Name
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_name =  "hardcode string valueu"; // change printable string here
    //end of hc-ranParameter_name -idx42- alias primitive

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 10
    //hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = -1 -optional
    // [STOP] recursive SEQUENCE RANParameter_Definition in stack
    //end of hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = -1
    /*=== END SEQUENCE -idx38 RANParameter-Definition-Choice-STRUCTURE-Item -ROOTS11 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE alias = -1
    /*=== END SEQUENCE -idx36 RANParameter-Definition-Choice-STRUCTURE -ROOTS10 ===*/

    #endif /*choice-ELEM 2 -idx35 -rootc3 - RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE */

    /*=== END CHOICE -rootc3 - RANParameter-Definition-Choice ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition alias = -1
    /*=== END SEQUENCE -idx23 RANParameter-Definition -ROOTS7 ===*/

    //end of hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = -1
    /*=== END SEQUENCE -idx17 RANParameter-Definition-Choice-LIST-Item -ROOTS6 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST alias = -1
    /*=== END SEQUENCE -idx15 RANParameter-Definition-Choice-LIST -ROOTS5 ===*/

    #endif /*choice-ELEM 1 -idx14 -rootc2 - RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST */

    #if 0 //hc-choice-ELEM 2 -idx44 -rootc2: RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choice_type = E2AP_RANPARAMETER_DEFINITION_CHOICE_e2ap_CHOICE_STRUCTURE;
    /*=== START SEQUENCE -idx45 -ROOTS12 RANParameter-Definition-Choice-STRUCTURE ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item_count = 1;
    /*=== START SEQUENCE -idx47 -ROOTS13 RANParameter-Definition-Choice-STRUCTURE-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx49- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx49- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 10 -mandatory
    //hc-ranParameter_name -idx51- alias primitive - pid = 10 PrintableString - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Name
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_name =  "hardcode string valueu"; // change printable string here
    //end of hc-ranParameter_name -idx51- alias primitive

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 10
    //hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = -1 -optional
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].bitmask |= E2AP_RANPARAMETER_DEFINITION_CHOICE_STRUCTURE_ITEM_e2ap_RAN_PARAMETER_DEFINITION_PRESENT;
    // [RECUSIVE] recursive - re-idx = 1 / SEQUENCE RANParameter_Definition detected in stack, continuing...
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition = xnap_mem_get(sizeof(_e2ap_RANParameter_Definition_t)); //memgetforrecu
    /*=== START SEQUENCE -idx53 -ROOTS14 RANParameter-Definition ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition alias = -1 -mandatory
    /*=== START CHOICE -rootc4 - RANParameter-Definition-Choice ===*/
    #if 1 //hc-choice-ELEM 1 -idx56 -rootc4: RANParameter-Definition-Choice->RANParameter_Definition_Choice_LIST - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choice_type = E2AP_RANPARAMETER_DEFINITION_CHOICE_e2ap_CHOICE_LIST;
    /*=== START SEQUENCE -idx57 -ROOTS15 RANParameter-Definition-Choice-LIST ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item_count = 1;
    /*=== START SEQUENCE -idx59 -ROOTS16 RANParameter-Definition-Choice-LIST-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx61- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx61- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 10 -mandatory
    //hc-ranParameter_name -idx63- alias primitive - pid = 10 PrintableString - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Name
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceLIST.ranParameter_List.RANParameter_Definition_Choice_LIST_Item[0].ranParameter_name =  "hardcode string valueu"; // change printable string here
    //end of hc-ranParameter_name -idx63- alias primitive

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = 10
    //hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = -1 -optional
    // [STOP] recursive SEQUENCE RANParameter_Definition in stack
    //end of hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item alias = -1
    /*=== END SEQUENCE -idx59 RANParameter-Definition-Choice-LIST-Item -ROOTS16 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST alias = -1
    /*=== END SEQUENCE -idx57 RANParameter-Definition-Choice-LIST -ROOTS15 ===*/

    #endif /*choice-ELEM 1 -idx56 -rootc4 - RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST */

    #if 0 //hc-choice-ELEM 2 -idx65 -rootc4: RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE - alias = -1
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choice_type = E2AP_RANPARAMETER_DEFINITION_CHOICE_e2ap_CHOICE_STRUCTURE;
    /*=== START SEQUENCE -idx66 -ROOTS17 RANParameter-Definition-Choice-STRUCTURE ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE alias = -1 -mandatory
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item_count = 1;
    /*=== START SEQUENCE -idx68 -ROOTS18 RANParameter-Definition-Choice-STRUCTURE-Item ===*/
    //hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 5 -mandatory
    //hc-ranParameter_ID -idx70- alias primitive - pid = 5 - INTEGER - min:1 - max:4294967295  - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-ID
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_ID = 2147483648;// change integer here
    //end of hc-ranParameter_ID -idx70- alias primitive
    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 5
    //hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 10 -mandatory
    //hc-ranParameter_name -idx72- alias primitive - pid = 10 PrintableString - E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Name
    p_E2SM_RC_QueryDefinition->ric_queryDefinition_formats.queryRequest_Format1.ranP_List.E2SM_RC_QueryDefinition_Format1_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_Definition->ranParameter_Definition_Choice.choiceSTRUCTURE.ranParameter_STRUCTURE.RANParameter_Definition_Choice_STRUCTURE_Item[0].ranParameter_name =  "hardcode string valueu"; // change printable string here
    //end of hc-ranParameter_name -idx72- alias primitive

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = 10
    //hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = -1 -optional
    // [STOP] recursive SEQUENCE RANParameter_Definition in stack
    //end of hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = -1
    /*=== END SEQUENCE -idx68 RANParameter-Definition-Choice-STRUCTURE-Item -ROOTS18 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE alias = -1
    /*=== END SEQUENCE -idx66 RANParameter-Definition-Choice-STRUCTURE -ROOTS17 ===*/

    #endif /*choice-ELEM 2 -idx65 -rootc4 - RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE */

    /*=== END CHOICE -rootc4 - RANParameter-Definition-Choice ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition alias = -1
    /*=== END SEQUENCE -idx53 RANParameter-Definition -ROOTS14 ===*/

    //end of hc-sequence-ELEM 3: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item alias = -1
    /*=== END SEQUENCE -idx47 RANParameter-Definition-Choice-STRUCTURE-Item -ROOTS13 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE alias = -1
    /*=== END SEQUENCE -idx45 RANParameter-Definition-Choice-STRUCTURE -ROOTS12 ===*/

    #endif /*choice-ELEM 2 -idx44 -rootc2 - RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE */

    /*=== END CHOICE -rootc2 - RANParameter-Definition-Choice ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition alias = -1
    /*=== END SEQUENCE -idx11 RANParameter-Definition -ROOTS4 ===*/

    //end of hc-sequence-ELEM 2: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item alias = -1
    /*=== END SEQUENCE -idx7 E2SM-RC-QueryDefinition-Format1-Item -ROOTS3 ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1 alias = -1
    /*=== END SEQUENCE -idx5 E2SM-RC-QueryDefinition-Format1 -ROOTS2 ===*/

    #endif /*choice-ELEM 1 -idx4 -rootc1 - E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1 */

    /*=== END CHOICE -rootc1 - E2SM-RC-QueryDefinition-ric-queryDefinition-formats ===*/

    //end of hc-sequence-ELEM 1: E2SM-RC-QueryDefinition alias = -1
    /*=== END SEQUENCE -idx1 E2SM-RC-QueryDefinition -ROOTS1 ===*/

    return XNAP_SUCCESS;
}
/*
E2SM-RC-QueryDefinition : (E2SM-RC-QueryDefinition) 					---- (SEQUENCE) ---- [UNK] ----PATH: E2SM-RC-QueryDefinition
    ric-queryDefinition-formats : (E2SM-RC-QueryDefinition-ric-queryDefinition-formats) 					---- (CHOICE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats
        queryRequest-Format1 : (E2SM-RC-QueryDefinition-Format1) 					---- (SEQUENCE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1
            ranP-List : (E2SM-RC-QueryDefinition-Format1-ranP-List) 					---- (SEQ-OF-ITEM) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List
                E2SM-RC-QueryDefinition-Format1-Item : (E2SM-RC-QueryDefinition-Format1-Item) 					---- (SEQUENCE) ---- [UNK] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item
                    ranParameter-ID : (RANParameter-ID) 					---- (PRIMITIVE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-ID
                    ranParameter-Definition : (RANParameter-Definition) 					---- (SEQUENCE) ---- [O] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition
                        ranParameter-Definition-Choice : (RANParameter-Definition-Choice) 					---- (CHOICE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice
                            choiceLIST : (RANParameter-Definition-Choice-LIST) 					---- (SEQUENCE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST
                                ranParameter-List : (RANParameter-Definition-Choice-LIST-ranParameter-List) 					---- (SEQ-OF-ITEM) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List
                                    RANParameter-Definition-Choice-LIST-Item : (RANParameter-Definition-Choice-LIST-Item) 					---- (SEQUENCE) ---- [UNK] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item
                                        ranParameter-ID : (RANParameter-ID) 					---- (PRIMITIVE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-ID
                                        ranParameter-name : (RANParameter-Name) 					---- (PRIMITIVE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Name
                                        ranParameter-Definition : (RANParameter-Definition) 					---- (RECURSIVE) ---- [O] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-LIST->RANParameter-Definition-Choice-LIST-ranParameter-List->RANParameter-Definition-Choice-LIST-Item->RANParameter-Definition
                            choiceSTRUCTURE : (RANParameter-Definition-Choice-STRUCTURE) 					---- (SEQUENCE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE
                                ranParameter-STRUCTURE : (RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE) 					---- (SEQ-OF-ITEM) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE
                                    RANParameter-Definition-Choice-STRUCTURE-Item : (RANParameter-Definition-Choice-STRUCTURE-Item) 					---- (SEQUENCE) ---- [UNK] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item
                                        ranParameter-ID : (RANParameter-ID) 					---- (PRIMITIVE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-ID
                                        ranParameter-name : (RANParameter-Name) 					---- (PRIMITIVE) ---- [M] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Name
                                        ranParameter-Definition : (RANParameter-Definition) 					---- (RECURSIVE) ---- [O] ----PATH: E2SM-RC-QueryDefinition->E2SM-RC-QueryDefinition-ric-queryDefinition-formats->E2SM-RC-QueryDefinition-Format1->E2SM-RC-QueryDefinition-Format1-ranP-List->E2SM-RC-QueryDefinition-Format1-Item->RANParameter-Definition->RANParameter-Definition-Choice->RANParameter-Definition-Choice-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-ranParameter-STRUCTURE->RANParameter-Definition-Choice-STRUCTURE-Item->RANParameter-Definition

RECURSION LIST:[]
RECURSION MARK LIST:{'RANParameter-Definition'}
*/
#endif // ASSIGN_HARDCODE_E2SM_RC_QUERY_DEFINITION_H

